# Use the official Nginx image to serve the static files
FROM nginx:alpine

# Set the working directory
WORKDIR /usr/share/nginx/html

# Copy the static files to the Nginx html directory
COPY ./src /usr/share/nginx/html

# Copy the Nginx configuration file
COPY ./conf/nginx.prod.conf /etc/nginx/conf.d/default.conf

# Expose the ports Nginx is running on
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
