# Use the official Nginx image to serve the static files
FROM nginx:alpine

# Copy the static files to the Nginx html directory
COPY ./src /usr/share/nginx/html

# Copy the environment-specific configuration file
COPY ./src/env/config.dev.js /usr/share/nginx/html/env/config.js

# Copy the Nginx configuration file
COPY ./conf/nginx.dev.conf /etc/nginx/conf.d/default.conf

# Expose the ports Nginx is running on
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
