# Use the official Nginx image to serve the static files
FROM nginx:alpine

# Copy the static files to the Nginx html directory
COPY ./src /usr/share/nginx/html

# Copy the Nginx configuration file
COPY ./conf/nginx.dev.conf /etc/nginx/conf.d/default.conf

# Copy the SSL certificate and key
COPY ./certs/dev.crt /etc/nginx/certs/dev.crt
COPY ./certs/dev.key /etc/nginx/certs/dev.key

# Expose the ports Nginx is running on
EXPOSE 80
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
